services:
  homepage:
    build:
      context: .
      args:
        NEXT_PUBLIC_SITE_NAME: ${NEXT_PUBLIC_SITE_NAME}
        NEXT_PUBLIC_SITE_TITLE: ${NEXT_PUBLIC_SITE_TITLE}
        NEXT_PUBLIC_SITE_DESCRIPTION: ${NEXT_PUBLIC_SITE_DESCRIPTION}
        NEXT_PUBLIC_GITHUB_USER: ${NEXT_PUBLIC_GITHUB_USER}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_REDDIT_READER_URL: ${NEXT_PUBLIC_REDDIT_READER_URL}
    container_name: homepage
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - CLUE_REVIEW_PASSWORD=${CLUE_REVIEW_PASSWORD}
